job/urls.py
from django.urls import path
from . import views
app_name = 'job'
urlpatterns = [
    path('' , views.job_list , name='job_list'),
    path('add/' , views.add_job , name='add_job'),
    path('<str:slug>/' , views.job_details , name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include

# form media files
# add this + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT) after ] 
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('jobs/', include('job.urls' , namespace='jobs')) ,
    path('admin/', admin.site.urls),
    path('contact-us/', include('contact.urls' , namespace='contact')) ,
    
] + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify

# auth in django
from django.contrib.auth.models import User
# Create your models here.

'''
django model fields
  - html widget
  -validations
  -db size
'''

#table as class
class Job(models.Model):  
    #choices
    JOB_TYPE = (
        ('FULL TIME','FULL TIME') ,
        ('PART TIME','PART TIME') ,
    )
    title = models.CharField(max_length=100)  #column
    # location 
    owner = models.ForeignKey(User , on_delete=models.CASCADE )
    job_type = models.CharField(max_length=15 , choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    # we but Category in '' cuz the model Category comes after Job model 
    # if Category model before Job model write like < category = models.ForeignKey(Category , ) > without ''
    category = models.ForeignKey('Category' , on_delete=models.CASCADE)

    image = models.ImageField(upload_to='jobs/')
    

    slug = models.SlugField(blank=True , null=True)

    def save(self , *args , **kwargs):
        self.slug = slugify(self.title)
        super(Job , self).save(*args , **kwargs)

    def __str__(self):
        return self.title



class Category(models.Model):
    name = models.CharField(max_length=25)
    def __str__(self):
        return self.name
    


class Apply(models.Model): 
    job = models.ForeignKey(Job , related_name='apply_job' , on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

job/views.py
from django.shortcuts import render ,redirect
# paginator
from django.core.paginator import Paginator
from .models import Job
from .form import ApplyForm , JobForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .filters import JobFilter

# Create your views here.


def job_list(request):
    # called models query set api used to get data from db {  ClassName.objects.all()  }
    job_list = Job.objects.all()

    ## Filters ##
    myfilter = JobFilter(request.GET , queryset=job_list)
    job_list = myfilter.qs

    # paginator
    paginator = Paginator(job_list, 3)  # Show 3 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    # return paginator and Filter in context
    return render(request , 'job/job_list.html' , {'jobs' : page_obj , 'myfilter':myfilter} )


def job_details(request , slug):
    # called (models query set api) used to get data from db {  ClassName.objects.get(ColumnName = param)  }
    job_detail = Job.objects.get(slug=slug)
    
    if request.method == 'POST' :
       form = ApplyForm(request.POST , request.FILES)
       if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job_detail
            myform.save()
    else :
        form =ApplyForm()
    return render(request , 'job/job_detail.html' , {'job' : job_detail , 'form' : ApplyForm} )


# decorators : u have function and u want it to pass some constraint to start it
# so when u r logged in add_job function will start
@login_required
def add_job(request):
    if request.method == 'POST' : 
        form = JobForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            # (request.user) refer to the current user
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))
    else :
        form =JobForm()

    return render(request , 'job/add_job.html' , {'form' : form})

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <!-- Apply for the job Form -->
                                    <!--  -->
                                    <form method="POST" class="form" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% bootstrap_form form %}
                                        {% buttons %}
                                        <button class="boxed-btn3 w-100" type="submit">Add job</button>
                                        {% endbuttons %}
                                      </form>
                                      <!--  -->
                        <!-- Apply for the job form end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{ job.image.url }}" style="width:75px; height:75px" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                                <p>{{job.description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <!-- Apply for the job Form -->
                        <h4>Apply for the job</h4>
                                    <!--  -->
                                    <form method="POST" class="form" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% bootstrap_form form %}
                                        {% buttons %}
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                        {% endbuttons %}
                                      </form>
                                      <!--  -->
                        <!-- Apply for the job form end -->
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}}k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span>{{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.paginator.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        {% comment %}  {% endcomment %}
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2" >
                            </form>
                        </div>
                        {% comment %}  {% endcomment %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{ job.image.url }}" style="width:75px; height:75px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date Line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
            {% comment %} paginatocr {% endcomment %}
                        {% if jobs.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>


                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}


                                            {% for i in jobs.paginator.page_range %}
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endfor %}


                                        {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}


                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
            {% comment %} paginatocr {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock body %}